from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from text_detector.east_text_detector import EastTextDetector
from text_detector.craft_text_detector import CraftTextDetector
from text_detector import text_detect_utils
from text_detector import third_party

